language: node_js
node_js:
- '9'
- '8'
- '7'
- '6'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH="$HOME/.yarn/bin:$PATH"
- yarn global add greenkeeper-lockfile@1
cache:
  yarn: true
  directories:
  - "~/.npm"
before_script:
- yarn global add npmvet david nsp depcheck types-checker
- greenkeeper-lockfile-update
after_script:
- greenkeeper-lockfile-upload
script:
- yarn verify
after_success:
- npm run semantic-release
- cat ./coverage/lcov.info | coveralls
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
